security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AuthentificationUtilisateurAuthenticator
            logout:
                path: app_logout
                target: accueil_app

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_EMPLOYEE] 

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN } 
        - { path: '^/employe', roles: ROLE_EMPLOYE }
