vich_uploader:
    db_driver: orm
    metadata:
        type: attribute 

    mappings:
       products:
           uri_prefix: /uploads/voiture
           upload_destination: '%kernel.project_dir%/public/assets/uploads/'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
